services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: ./Dockerfile
    image: nginx:shtanemu
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    hostname: ${DOMAIN_NAME}
    tty: true
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html:ro
      - ${CERTS_}:/etc/nginx/ssl
    depends_on:
      - wordpress
    restart: always
    networks:
      - docker-network
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: ./Dockerfile
    image: wordpress:shtanemu
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    working_dir: /var/www/html
    restart: always
    networks:
      - docker-network
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
  mariadb:
    container_name: mariadb
    build:
      dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb:shtanemu
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
  redis:
    container_name: redis
    build:
      dockerfile: ./requirements/redis/Dockerfile
    image: redis:shtanemu
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    networks:
      - docker-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  ftp:
    container_name: ftp
    build:
      dockerfile: ./requirements/ftp/Dockerfile
    image: ftp:shtanemu
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress:/var/www/html
    environment:
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
    restart: always
  adminer:
    container_name: adminer
    build:
      dockerfile: ./requirements/adminer/Dockerfile
    image: adminer:shtanemu
    networks:
      - docker-network
  website:
    container_name: website
    build:
      dockerfile: ./requirements/website/Dockerfile
    image: website:shtanemu
    networks:
      - docker-network
  cadvisor:
    build:
      dockerfile: ./requirements/cadvisor/Dockerfile
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment:
      DEBUG: ${DEBUG}
    restart: on-failure
volumes:
  wordpress:
  mariadb:
networks:
  docker-network:
    driver: bridge
