version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./srcs
      dockerfile: ./requirements/nginx/Dockerfile
    image: nginx:shtanemu
    ports:
      # For debug
      # - '80:80'
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
volumes:
  wordpress:
networks:
  inception_network:
    driver: bridge
