version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./srcs
      dockerfile: ./requirements/nginx/Dockerfile
    image: nginx:shtanemu
    ports:
      # For debug
    volumes:
      - wordpress:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - inception_network
  wordpress:
    container_name: wordpress
    build:
      context: ./srcs
      dockerfile: ./requirements/wordpress/Dockerfile
    image: wordpress:shtanemu
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    working_dir: /var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    container_name: mariadb
    build:
      context: ./srcs
      dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb:shtanemu
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
volumes:
  wordpress:
networks:
  inception_network:
    driver: bridge
