version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./srcs
      dockerfile: ./requirements/nginx/Dockerfile
    image: nginx:shtanemu
    ports:
      # For debug
      # - '80:80'
    networks:
      - inception_network
    networks:
      - inception_network
networks:
  inception_network:
    driver: bridge
