version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./srcs
      dockerfile: ./requirements/nginx/Dockerfile
    image: nginx:shtanemu
    tty: true
    ports:
      # For debug
      - '80:80'
    volumes:
      - wordpress:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - docker-network
  wordpress:
    container_name: wordpress
    build:
      context: ./srcs
      dockerfile: ./requirements/wordpress/Dockerfile
    image: wordpress:shtanemu
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    working_dir: /var/www/html
    networks:
      - docker-network
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    container_name: mariadb
    build:
      context: ./srcs
      dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb:shtanemu
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
volumes:
  wordpress:
  mariadb:
networks:
  docker-network:
    driver: bridge
